### PR TITLE
Fixed super cryptic discord error 'embeds=[0]'. turns out it was just…

### PR DESCRIPTION
**Pull request by rszemplinski**
… a avatar url issue where if it was gitlabs avatar url it wasn't a proper url and just a path for gitlab to retrieve it. Also added some stuff for heroku users in the config.example.js for easy setup

### CODE REVIEW

**Comment by rszemplinski** [comment]
Will this be merged soon?

**Comment by rszemplinski** [comment]
@jellysquid3 do you mind merging this?

**Comment by jellysquid3** [comment]
Apologies. I don't actively maintain this project at the moment, and email notifications for this thread weren't being delivered correctly to my inbox. 

Besides that, this PR looks solid to me.

**Comment by rszemplinski** [comment]
Thanks! :)

**Pull request merged**
